<?php

use Nette\Utils\Arrays;
use WebChemistry\TaskRunner\ITaskRunner;
use WebChemistry\TaskRunner\Utility\TaskRunnerUtility;

/** @var ITaskRunner $taskRunner */
?>

<h1>Tasks</h1>

<table class="tracy-sortable">
	<thead>
		<tr>
			<th>Class</th>
			<th>Name</th>
			<th>Groups</th>
			<th>Cmd</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($taskRunner->getTasks() as $task): ?>
		<tr>
			<td><?= $task::class ?></td>
			<td><span style="cursor: pointer" class="tracy-taskRunner-copy"><?= TaskRunnerUtility::getTaskName($task) ?></span></td>
			<td>
				<?php if ($groups = TaskRunnerUtility::getTaskGroups($task)): ?>
					<?php if (count($groups) === 1): ?>
						<span style="cursor: pointer" class="tracy-taskRunner-copy"><?= Arrays::first($groups) ?></span>
					<?php else: ?>
						<table>
							<tbody>
								<?php foreach ($groups as $group): ?>
								<tr>
									<td><span style="cursor: pointer" class="tracy-taskRunner-copy"><?= $group ?></span></td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					<?php endif ?>
				<?php endif ?>
			</td>
			<td>
				<a href="#" class="tracy-taskRunner-cmd-copy" data-name="<?= strtr($task::class, ['\\' => '/']) ?>">copy</a>
			</td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>

<div style="margin-top: 8px">
	Default command (editable): <input type="text" id="tracy-taskRunner-input">
</div>

<script>
	(function () {
		function getTemplate() {
			const template = window.localStorage.getItem('tracy.taskRunner.defaultCommand');

			if (!template) {
				return 'console task:run %s%';
			}

			return template;
		}

		const input = document.getElementById('tracy-taskRunner-input');

		input.value = getTemplate();
		input.addEventListener('keyup', function (e) {
			window.localStorage.setItem('tracy.taskRunner.defaultCommand', e.currentTarget.value);
		});

		document.addEventListener('click', function (event) {
			if (event.target.className === 'tracy-taskRunner-copy') {
				navigator.clipboard.writeText(event.target.innerText.trim());
			}
		});

		document.addEventListener('click', function (event) {
			event.preventDefault();

			if (event.target.className === 'tracy-taskRunner-cmd-copy') {
				navigator.clipboard.writeText(getTemplate().replace('%s%', `"${event.target.dataset.name}"`));
			}
		});
	})();
</script>
