<?php

use Nette\Utils\Arrays;
use WebChemistry\TaskRunner\IScheduledTask;
use WebChemistry\TaskRunner\ITaskRunner;
use WebChemistry\TaskRunner\Tracy\TaskRunnerBar;
use WebChemistry\TaskRunner\Utility\TaskRunnerUtility;

/** @var ITaskRunner $taskRunner */
/** @var TaskRunnerBar $this */
/** @var string $command */
?>

<h1>Tasks</h1>

<table class="tracy-sortable">
	<thead>
		<tr>
			<th>Class</th>
			<th>ID</th>
			<th>Schedule</th>
			<th>Cmd</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->groups($taskRunner) as $id => $group): ?>
			<?php foreach ($group as $task): ?>
			<tr>
				<td><?= $task::class ?></td>
				<td><span style="cursor: pointer" class="tracy-taskRunner-copy"><?= $task->getId() ?? ($id ?: 'null') ?></span></td>
				<td><?= $task instanceof IScheduledTask ? $task->getSchedule()->getNormalized() : '' ?></td>
				<td>
					<a href="#" class="tracy-taskRunner-cmd-copy" data-name="<?= strtolower(strtr($task::class, ['\\' => '/'])) ?>">copy</a>
				</td>
			</tr>
			<?php endforeach ?>
		<?php endforeach ?>
	</tbody>
</table>

<script>
	(function () {
		const template = <?= json_encode($command) ?>

		document.addEventListener('click', function (event) {
			if (event.target.className === 'tracy-taskRunner-copy') {
				navigator.clipboard.writeText(event.target.innerText.trim());
			}
		});

		document.addEventListener('click', function (event) {
			event.preventDefault();

			if (event.target.className === 'tracy-taskRunner-cmd-copy') {
				navigator.clipboard.writeText(template.replace('%s%', `"${event.target.dataset.name}"`));
			}
		});
	})();
</script>
